"""added chat

Revision ID: 0fe630f31e20
Revises: 5e835e4b5976
Create Date: 2025-07-07 04:04:41.515714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe630f31e20'
down_revision: Union[str, None] = '5e835e4b5976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('chat_title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index(op.f('ix_chat_ids_course_id'), 'chat_ids', ['course_id'], unique=False)
    op.create_index(op.f('ix_chat_ids_user_id'), 'chat_ids', ['user_id'], unique=False)
    op.drop_table('ChatID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatID',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chat_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name='ChatID_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ChatID_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ChatID_pkey')
    )
    op.drop_index(op.f('ix_chat_ids_user_id'), table_name='chat_ids')
    op.drop_index(op.f('ix_chat_ids_course_id'), table_name='chat_ids')
    op.drop_table('chat_ids')
    # ### end Alembic commands ###
