"""added document_id and update_id in courseContent

Revision ID: 384f1d0b3442
Revises: 34f029366afe
Create Date: 2025-07-06 22:07:16.460968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384f1d0b3442'
down_revision: Union[str, None] = '34f029366afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_content', sa.Column('vectera_document_id', sa.String(), nullable=False))
    op.add_column('course_content', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_content', 'updated_at')
    op.drop_column('course_content', 'vectera_document_id')
    # ### end Alembic commands ###
