"""feedback rating

Revision ID: 46948ab4bc58
Revises: 2030fc852183
Create Date: 2025-06-22 23:34:08.065189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46948ab4bc58'
down_revision: Union[str, None] = '2030fc852183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_feedback', sa.Column('rating', sa.Integer(), nullable=False))
    op.alter_column('course_feedback', 'feedback_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_feedback', 'feedback_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('course_feedback', 'rating')
    # ### end Alembic commands ###
