"""Updated user and course model

Revision ID: 46ba4f5bc61c
Revises: cb2883dabbf6
Create Date: 2025-06-15 04:56:10.224612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ba4f5bc61c'
down_revision: Union[str, None] = 'cb2883dabbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profilePicture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePicture')
    op.drop_column('courses', 'course_image')
    # ### end Alembic commands ###
