"""added document_id nullable

Revision ID: da960d62453d
Revises: 384f1d0b3442
Create Date: 2025-07-06 22:27:56.156131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da960d62453d'
down_revision: Union[str, None] = '384f1d0b3442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_content', 'vectera_document_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_content', 'vectera_document_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
