"""Updated enrollments and course model

Revision ID: f8f309f3a736
Revises: 46ba4f5bc61c
Create Date: 2025-06-15 16:04:41.241090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f309f3a736'
down_revision: Union[str, None] = '46ba4f5bc61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_status', sa.String(), nullable=True))
    op.add_column('enrollments', sa.Column('enrollment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'enrollment_status')
    op.drop_column('courses', 'course_status')
    # ### end Alembic commands ###
